baseURL = "https://jdiazgutierrez.github.io"

# set your your own ga token here.
googleAnalytics = "G-ZFHJD0R5JD"

languageCode = "en-us"

# for using avicenna you need to set the themes to 'avicenna'
enableEmoji = true
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Julian Diaz-Gutierrez"

# number of posts to show on the blog page
paginate = 10

# publishing directory
publishDir = "public"



[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[params]
# it is used for the copy-right section of your page
name = "Julian Diaz-Gutierrez"

# used favicon image 
Favicon = "favicon.ico"

# additional social links
  [params.social]
    lens = "https://www.lens.org/lens/profile/"
    dataverse = "https://dataverse.harvard.edu/dataverse/"

